# Generated by Django 5.0 on 2024-03-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(default='', max_length=20)),
                ('LastName', models.CharField(default='', max_length=20)),
                ('Mail', models.CharField(default='', max_length=50)),
                ('Number', models.IntegerField(default='')),
                ('Message', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
